### ISSUE TITLE
Meta-issue: Java Operator

### ISSUE THREAD

**Issue by jmrodri** [operator-framework/java-operator-plugins#1]
The Operator SDK maintainers, Red Hat Middleware and Container Solutions are working hard to build a community around the Java operator.

This is a meta-issue to track the work to get the project ready.

### Reaching alpha
- [x] Move [jmrodri/kubebuilder-plugin](https://github.com/jmrodri/kubebuilder-plugin) to this repo assigned to @jmrodri (https://github.com/operator-framework/java-operator/commit/9e37ab103dddc8379b19be6e6cefa81b18160eaf)
- [x] Rename github.com/operator-framework/java-operator to github.com/operator-framework/java-operator-plugins @jmrodri
- [x] Once here rename packages for the above project to match its new home i.e. `github.com/operator-framework/java-operator-plugins` @jmrodri
- [x] Change version from `v1` to `v1-alpha` (updated version) @jmrodri (#5)
- [x] Add necessary bits to scaffolding to start informers/watches assigned to @laxmikantbpandhare 
- [x] Tie project into Github Actions @jmrodri (#14) 
- [x] Write a tutorial to document how to use the plugin to create an operator project @laxmikantbpandhare (#10) @jmrodri (#18)
- [x] Submit PR to integrate with  [Operator SDK](https://github.com/operator-framework/operator-sdk/) @laxmikantbpandhare ([4871](https://github.com/operator-framework/operator-sdk/pull/4871))
- [x] change javav1 to quarkusv1 in the instructions @sujil02 (#4)
- [x] change javabundle to quarkusBundle @sujil02  (#4)
- [x] change the title of Java Operator SDK to Java Operator Plugins @sujil02  (#4)
- [x] change the heading level of "Enable kubebuilder-plugin" to be the same as License so they look the same size @sujil02  (#4)
- [x] rename "kubebuilder-plugin" to java-operator-plugins @sujil02  (#4)

### Longer term community items
- [ ] Create a plain old java plugin in this same repo alongside the quarkus one.
- [x] Community guidelines: [(#2)](https://github.com/operator-framework/java-operator/pull/2)
- [ ] Setup community chairs
- [ ] Setup community meetings
- [ ] PR review process
- [ ] How to become a reviewer and approver
- [ ] Docs section and procedure for how tos etc
- [ ] Testing
- [ ] Samples: where and what to include
- [ ] Scaffolding commands
- [ ] Write scaffolder plugin to scaffold out Java project in Quarkus
- [x] Setup issue templates
- [ ] Add standard plugin config to project @jmrodri

**Comment by austince** [comment]
What is the relation of this project to [`java-operator-sdk/java-operator-sdk`](https://github.com/java-operator-sdk/java-operator-sdk)? Have I missed this note somewhere? It seems they are both active.

**Comment by jmrodri** [comment]
@austince Sorry I didn't see your question earlier. This project is aiming to create a plugin for the [Operator Frameworks' Operator SDK](https://github.com/operator-framework/operator-sdk/). The intent is to scaffold out an operator in Java. We actually plan on using [`java-operator-sdk/java-operator-sdk`](https://github.com/java-operator-sdk/java-operator-sdk) in our scaffolding.

We've got a prototype that was started in another repo that I plan to move here instead.

**Comment by austince** [comment]
Ah ok, that makes sense – thanks for the clarification + looking forward to it!

**Comment by estroz** [comment]
Some questions:

>Once here rename packages for the above project to match its new home i.e. `github.com/operator-framework/java-operator`

There is no "java-operator", as there is for ansible/helm, so is kinda confusing. Perhaps a better choice is to stick with `java-operator-sdk`, or `java-operator-plugins`.

>Change version from v1 to v1alpha1

You mean `v1` to `v1-alpha` right? For context, plugin version scheme != k8s version scheme.

>Create a plain old java plugin in this same repo alongside the quarkus one.

This does not sound like an alpha requirement for a Java plugin; vanilla Java and Quarkus are completely separate plugins. Which will be alpha'd in operator-sdk first? It sounds like vanilla Java based on other requirements.

**Comment by jmrodri** [comment]
> Some questions/comments:
> 
> > Once here rename packages for the above project to match its new home i.e. `github.com/operator-framework/java-operator`
> 
> There is no "java-operator", as there is for ansible/helm, so is kinda confusing. Perhaps a better choice is to stick with `java-operator-sdk`, or `java-operator-plugins`.

I think `java-operator-sdk` would be confusing since there is already an org and project called that. The name `java-operator` came from the same of `ansible-operator` and `helm-operator`, but I can see your point. Then I I would prefer `java-operator-plugins` instead then as that is more descriptive of what this actually is.

> 
> > Change version from v1 to v1alpha1
> 
> You mean `v1` to `v1-alpha` right? For context, plugin version scheme != k8s version scheme.
:smile: fair point, I will change the bullet point to be `v1-alpha`

> 
> > Create a plain old java plugin in this same repo alongside the quarkus one.
> 
> This does not sound like an alpha requirement for a Java plugin; vanilla Java and Quarkus are completely separate plugins. Which will be alpha'd in operator-sdk first? It sounds like vanilla Java based on other requirements.

I added this requirement but this probably does not have to be part of the first alpha and could occur at a later date.
